### PR TITLE
refactor: remove unused `angularUpdater` file

### LINKED ISSUE #111: `AngularUpdate` class is not used in the codebase
@duluca during working with the codebase of the extension, I noticed that `angularUpdater.ts` is not used in the code. Is this something that could be removed or deprecated somehow? Thanks!

### PR DESCRIPTION
**Pull request by bampakoa**
Closes #111

### CODE REVIEW

**Comment by duluca** [comment]
@bampakoa Build is failing on `npx audit-ci --high --report-type full`

**Comment by bampakoa** [comment]
@duluca I run `npm audit fix` locally, fixed some packages, but there are some that could not be fixed:

```
Failed security audit due to critical, high vulnerabilities.
Vulnerable advisories are:
https://github.com/advisories/GHSA-ww39-953v-wcq6
https://github.com/advisories/GHSA-xvch-5gv4-984h
https://github.com/advisories/GHSA-93q8-gq69-wqmw
```

**Comment by duluca** [comment]
> @duluca I run `npm audit fix` locally, fixed some packages, but there are some that could not be fixed:
> 
> ```
> Failed security audit due to critical, high vulnerabilities.
> Vulnerable advisories are:
> https://github.com/advisories/GHSA-ww39-953v-wcq6
> https://github.com/advisories/GHSA-xvch-5gv4-984h
> https://github.com/advisories/GHSA-93q8-gq69-wqmw
> ```

I'll take a look and push the PR through. Thanks

**Comment by bampakoa** [comment]
@duluca any news on the audit issues? I tried to fix them again with no luck 😟

**Pull request closed without merging**
