### PR TITLE
#46: Create sidebar menu and display icon for evergreen

### LINKED ISSUE #46: Sidebar Menu: Create sidebar menu
There needs to be a menu for any menu tasks

### PR DESCRIPTION
**Pull request by alexhoffman617**
-Created Icon for side view display
-update package.json to display Evergreen sidemenu
resolves #46

### CODE REVIEW

**Comment by alexhoffman617** [comment]
Shouldnt be merged until we are ready to add functionality for the sidebar as well

**Comment by duluca** [comment]
Hold until #9 is merged

**Comment by duluca** [comment]
@alexhoffman617 can you resolve the merge conflict?

**Comment by alexhoffman617** [comment]
> @alexhoffman617 can you resolve the merge conflict?

@duluca fixed merged conflicts for my branches

**Pull request merged**
