### PR TITLE
Add @types/vscode and vscode-test

### PR DESCRIPTION
**Pull request by brendoncaulkins**
Per https://www.npmjs.com/package/vscode the single package is being deprecated in favor of two packages.  This PR aligns Angular Evergreen with the new structure, without any notable adverse effects (from what I could tell).

### CODE REVIEW

**Comment by duluca** [comment]
@brendoncaulkins how compatible/incompatible is this with https://github.com/expertly-simple/angular-evergreen/pull/66? cc @kentonbmax

**Comment by brendoncaulkins** [comment]
@duluca @kentonbmax Rebased off master, minor tweaks needed.  This is good to go.

**Comment by kentonbmax** [comment]
Will look tonight.

**Comment by kentonbmax** [comment]
@brendoncaulkins do the existing jasmine tests still function or do they need to be removed? If so please do the necessary.

**Comment by duluca** [comment]
@kentonbmax if you'd like to ensure that the tests always remain in working condition add it to the circleci yml file, so the CI server can execute them

**Comment by kentonbmax** [comment]
Great Idea, but looks like BC removed jasmine in favor of extension tests.
Will sync with him.

**Comment by brendoncaulkins** [comment]
We can't mix Jasmine and Mocha, their types collide, so we have to pick one or the other.  I went with mocha, since that's what the examples used with the new `vscode-test` package.  I'd probably prefer Jasmine over mocha just from a familiarity stand point, but I was going for the quick win, thinking we could figure out how to bring Jasmine back in later.

And maybe later is now?

**Comment by kentonbmax** [comment]
@brendoncaulkins I would say convert the existing relevant tests to mocha so we can properly follow the vscode testing model. Please do the necessary.

**Pull request merged**
